<?php
/**
 * Must Use Plugin to suppress _load_textdomain_just_in_time notices
 * Auto-generated by WPHaven Connect plugin
 * 
 * This file is automatically managed. Do not edit manually.
 * To disable: set WPH_SUPPRESS_TEXTDOMAIN_NOTICES to false in wp-config.php
 * or remove this file and set the constant to false.
 */

if (!defined('ABSPATH')) {
    exit;
}

// Check if we should suppress textdomain notices
$suppress_textdomain = defined('WPH_SUPPRESS_TEXTDOMAIN_NOTICES') ? WPH_SUPPRESS_TEXTDOMAIN_NOTICES : null;

// If not explicitly set, check environment
if ($suppress_textdomain === null) {
    // Quick environment check
    $env = 'production';
    if (function_exists('wp_get_environment_type')) {
        $env = wp_get_environment_type();
    } elseif (defined('WP_ENVIRONMENT_TYPE')) {
        $env = WP_ENVIRONMENT_TYPE;
    } elseif (defined('WP_ENV')) {
        $env = WP_ENV;
    }

    // Normalize
    if ($env === 'local')
        $env = 'development';

    $suppress_textdomain = ($env === 'development');
}

if ($suppress_textdomain) {
    add_filter('doing_it_wrong_trigger_error', function ($trigger, $function_name, $message, $version) {
        // Suppress _load_textdomain_just_in_time notices in development
        if (
            '_load_textdomain_just_in_time' === $function_name ||
            strpos($message, '_load_textdomain_just_in_time') !== false ||
            strpos($message, 'Translation loading') !== false
        ) {
            return false; // Suppress this notice
        }
        return $trigger;
    }, 10, 4);
}
